version: '3'
services:
  influxdb:
    image: influxdb:1.8-alpine 
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=energy
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=testadmin
    #restart: always
  grafana:
    image: grafana/grafana:latest
    ports:
       - '3000:3000'
    volumes:
       - grafana-storage:/var/lib/grafana
       - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
        - influxdb
    environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=testadmin
    #restart: always
volumes:
  influxdb-storage:
  grafana-storage:
